### PR TITLE
Add a new game to the project

### PR DESCRIPTION
**Pull request by timotheeMM**
Hello @Yashwanth-Kumar-Kurakula,
I hope you’re all right.
Well done for this project, it’s a very good idea.
I added a CLI hangman game.
This is how it works:
- First, we load the word list into the main.py.
- One word is chosen randomly.
- Put "_" instead of letters that have not yet been guessed.
- The number of remaining tests is displayed.
- The user is asked to enter a letter.
- If it is a letter contained in the word, it is displayed.
- If not a message tells the user that he was wrong.
- If it was the last try, the output message is displayed.

Feel free to tell me if I need to change anything else... :blush:
Timothée
Ps: In the README.md, you say that you have to start the commits by a lowercase letter, but you do not, you should perhaps modify it.

### CODE REVIEW

**Comment by yakuraku** [comment]
Hi @timotheeMM ! I'm doing well, and I hope you're also giving your best effort! Thank you for including Hangman in the project. Feel free to share any of your beginner or intermediate-level Python programs as well; they could be valuable to someone in the future! 😊

Regarding the readme file majority of it is taken from your readme file for youtube downloader. I found it better than what I could manage to write 😉. I will update it soon. 

Have a wonderful day!

**Comment by timotheeMM** [comment]
@Yashwanth-Kumar-Kurakula. I’m looking for another game idea. Could you give me one to add to your project? I’m not doing anything specific right now.

**Comment by yakuraku** [comment]
@timotheeMM. I am currently working on GUI version of Snake game and Pong game, Here are what I would suggest:
1. Blackjack
2. Minesweeper
3. 2048
4. memory matching game 

But of course, you can go ahead with any other game as well, looking forward to playing your game! 😁

**Comment by timotheeMM** [comment]
@Yashwanth-Kumar-Kurakula,
For the snake game, I advise you to take a look from my repo [snake-game](https://github.com/timotheeMM/snake-game). It is coded with Javascript, but you can take inspiration from the game logic.

**Comment by yakuraku** [comment]
Thanks @timotheeMM ! I will definitely take a look

**Pull request merged**
